name: Build Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permissao de execucao ao gradlew
        run: chmod +x gradlew

      - name: Compilar com o Gradle
        run: ./gradlew build --no-daemon

      - name: Disponibilizar o jar pronto para download
        uses: actions/upload-artifact@v4
        with:
          name: meupack-java-addon
          path: build/libs/*.jar
